---
namespace: community
name: webapp-role
version: 1.0.0
readme: README.md
authors:
  - Flavien Annaix
description: Install webapp
license_file: COPYING
tags:
  - v1
repository: https://github.com/Flav1-ann/webapp_role.git
documentation: https://github.com/Flav1-ann/webapp_role.git
homepage: https://github.com/Flav1-ann/webapp_role.git
issues: https://github.com/Flav1-ann/webapp_role.git
build_ignore:
  - .gitignore